// SessionCoordinator.swift — applies SessionEffect side effects to services and window controllers (canon §2, §5).
//
// Thin glue: the reducer decides everything, the coordinator only executes ordered effects against
// the window controllers, timer, audio, and presence services. It calls back into AppState.send for
// events generated by those services (timer ticks, presence, countdown completion, UI button taps).

import AppKit
import SwiftUI

final class SessionCoordinator {
    weak var appState: AppState?

    private let settings: SettingsStore
    private let store: SessionStore
    private let screen = ScreenManager()

    // Services
    private let voice: VoicePrompting = VoicePromptService()
    private let alarm: AlarmPlaying = AlarmService()
    private let simulated = SimulatedPresenceService()
    private let permission = CameraPermissionService()
    private var presence: PresenceDetecting?
    private let timer = SessionTimer()

    // Window controllers
    private lazy var orb = FocusOrbWindowController(
        app: appState!, positionStore: OrbPositionStore(settings: settings), screen: screen)
    private let aura: AuraWindowController

    // Transient windows
    private var startPanel: NSPanel?
    private var countdownWindow: NSWindow?
    private var hudPanel: NSPanel?
    private var awayPanel: NSPanel?
    private var completionPanel: NSPanel?
    private var settingsWindow: NSWindow?
    private var historyWindow: NSWindow?
    private var onboardingWindow: NSWindow?

    init(settings: SettingsStore, store: SessionStore) {
        self.settings = settings
        self.store = store
        self.aura = AuraWindowController(settings: settings, screen: screen)

        timer.onTick = { [weak self] delta in self?.appState?.send(.tick(deltaSeconds: delta)) }
        screen.onScreenParametersChanged = { [weak self] in
            self?.orb.clampIntoVisibleBounds()
            self?.aura.rebuildWindows()
        }
        screen.startObservingScreenChanges()
    }

    /// Called by AppState after it constructs the coordinator, once `appState` is available.
    /// Wires the orb here (not in init) because the lazy orb needs a non-nil `appState`.
    func attach(_ appState: AppState) {
        self.appState = appState
        orb.onClick = { [weak self] in self?.appState?.send(.orbClicked) }
        orb.onSecondaryClick = { [weak self] event in self?.showOrbQuickActions(event) }
    }

    // MARK: Orb + menu-driven windows

    func showOrb() { orb.show() }

    func showSettings() {
        guard let app = appState else { return }
        if let w = settingsWindow { present(w); return }
        let view = SettingsView(
            onClearData: { [weak self] in try? self?.store.clear() },
            onResetOrb: { [weak self] in self?.orb.resetToDefault() },
            onOpenSystemCamera: { Self.openSystemCameraPrefs() }
        ).environmentObject(app)
        let w = makeStandardWindow(title: "Hyperfocus Settings", view: view)
        settingsWindow = w
        present(w)
    }

    func showHistory() {
        historyWindow?.orderOut(nil)
        let view = HistoryView(sessions: store.all())
        let w = makeStandardWindow(title: "Session History", view: view)
        historyWindow = w
        present(w)
    }

    func showOnboarding() {
        let view = OnboardingView(onFinish: { [weak self] in
            self?.settings.onboardingCompleted = true
            self?.onboardingWindow?.orderOut(nil)
            self?.onboardingWindow = nil
        })
        let w = makeStandardWindow(title: "Welcome to Hyperfocus", view: view)
        onboardingWindow = w
        present(w)
    }

    // MARK: Effect execution

    func perform(_ effects: [SessionEffect]) {
        for effect in effects { apply(effect) }
    }

    private func apply(_ effect: SessionEffect) {
        switch effect {
        case .showStartCard:            showStartCard()
        case .hideStartCard:            dismiss(&startPanel)
        case .showCountdown:            showCountdown()
        case .dismissCountdown:         dismiss(&countdownWindow)
        case .setAura(let state):       aura.setState(state)
        case .startTimer:               appState?.markTimerStarted(); timer.start(); showHUD()
        case .pauseTimer, .resumeTimer: break   // SessionTimer is a continuous heartbeat; the reducer accounts per state
        case .stopTimer:                appState?.markSessionEnded(); timer.stop(); dismiss(&hudPanel)
        case .startCameraWarmup:        startPresence(warmup: true)
        case .startPresenceDetection:   startPresence(warmup: false)
        case .stopCamera:               presence?.stop(); presence = nil
        case .startAlarm:               if settings.alarmEnabled { alarm.start(volume: alarmVolume()) }
        case .stopAlarm:                alarm.stop()
        case .playVoice(let line):      if settings.voicePromptsEnabled { voice.speak(line, style: settings.voiceStyle) }
        case .showAwayCard:             showAwayCard()
        case .hideAwayCard:             dismiss(&awayPanel)
        case .showRecoveryCountdown, .hideRecoveryCountdown: break   // AwayModeView reacts to state == .recovering
        case .showCompletion:           showCompletion()
        case .hideCompletion:           dismiss(&completionPanel)
        case .saveSession(let status):  appState?.persist(status)
        case .orbFlash:                 break   // FocusOrbView reacts to the state change to .idle
        }
    }

    // MARK: Presence

    private func startPresence(warmup: Bool) {
        let usingSimulated = appState?.useSimulatedCamera ?? false
        if presence == nil {
            let service: PresenceDetecting = usingSimulated ? simulated : CameraPresenceService()
            service.onEvent = { [weak self] event in
                switch event {
                case .facePresent:          self?.appState?.send(.facePresenceChanged(true))
                case .faceMissing:          self?.appState?.send(.facePresenceChanged(false))
                case .cameraState(let s):   self?.appState?.send(.cameraStateChanged(s))
                }
            }
            presence = service
        }
        // Real camera: request permission first so the capture session can actually start (and the
        // camera indicator turns on). If denied, the service emits .notAuthorized → reducer degrades
        // to no-camera semantics. Simulated camera needs no permission.
        if usingSimulated {
            beginPresence(warmup: warmup)
        } else {
            permission.requestAccess { [weak self] _ in self?.beginPresence(warmup: warmup) }
        }
    }

    private func beginPresence(warmup: Bool) {
        if warmup { presence?.startWarmup() } else { presence?.startDetection() }
    }

    private func alarmVolume() -> Float {
        let base = Float(settings.soundVolume)
        let mult = Float(Constants.IntensityTuning.alarmVolumeMultiplier(
            for: appState?.context.config?.intensity ?? .cinematic))
        return min(1, base * mult)
    }

    // MARK: Cards

    private func showStartCard() {
        guard startPanel == nil, let app = appState else { return }
        let view = StartSessionView(
            onStart: { [weak self] config in self?.appState?.send(.enterHyperfocus(config)) },
            onCancel: { [weak self] in self?.appState?.send(.cancelPreparing) }
        )
        let panel = makeCardPanel(view, app: app, level: .statusBar)
        placeNearOrb(panel)
        startPanel = panel
        NSApp.activate(ignoringOtherApps: true)
        panel.makeKeyAndOrderFront(nil)
    }

    private func showCountdown() {
        guard countdownWindow == nil, let app = appState else { return }
        let frame = screen.mainScreenFrame()
        let view = CountdownOverlayView(
            onFinished: { [weak self] in self?.appState?.send(.countdownCompleted) },
            onAbort: { [weak self] in self?.appState?.send(.userExited) }
        ).environmentObject(app)

        let window = KeyablePanel(contentRect: frame, styleMask: [.borderless, .nonactivatingPanel],
                                  backing: .buffered, defer: false)
        window.isOpaque = false
        window.backgroundColor = .clear
        window.hasShadow = false
        window.level = .screenSaver
        window.collectionBehavior = [.canJoinAllSpaces, .fullScreenAuxiliary]
        window.isReleasedWhenClosed = false
        let host = NSHostingView(rootView: view)
        host.frame = CGRect(origin: .zero, size: frame.size)
        host.autoresizingMask = [.width, .height]
        window.contentView = host
        window.setFrame(frame, display: true)
        countdownWindow = window
        NSApp.activate(ignoringOtherApps: true)
        window.makeKeyAndOrderFront(nil)      // key so Esc (onExitCommand) aborts
    }

    private func showHUD() {
        guard hudPanel == nil, let app = appState else { return }
        let view = ActiveHUDView(onExit: { [weak self] in self?.appState?.send(.userExited) })
        let panel = makeCardPanel(view, app: app, level: .statusBar)
        placeNearOrb(panel)
        hudPanel = panel
        panel.orderFrontRegardless()
    }

    private func showAwayCard() {
        guard awayPanel == nil, let app = appState else { return }
        let view = AwayModeView(
            onReturn: { [weak self] in self?.appState?.send(.facePresenceChanged(true)) },
            onExit: { [weak self] in self?.appState?.send(.userExited) }
        )
        let panel = makeCardPanel(view, app: app, level: .screenSaver)
        center(panel)
        awayPanel = panel
        NSApp.activate(ignoringOtherApps: true)
        panel.orderFrontRegardless()
    }

    private func showCompletion() {
        guard completionPanel == nil, let app = appState else { return }
        let view = CompletionView(onResult: { [weak self] status, next in
            self?.appState?.send(.resultSaved(status, nextAction: next))
        })
        let panel = makeCardPanel(view, app: app, level: .floating)
        center(panel)
        completionPanel = panel
        NSApp.activate(ignoringOtherApps: true)
        panel.makeKeyAndOrderFront(nil)
    }

    private func showOrbQuickActions(_ event: NSEvent) {
        let menu = NSMenu()
        let running = appState?.context.state.isRunning ?? false
        if appState?.context.state == .active {
            menu.addItem(withTitle: Constants.Copy.orbActionPause, action: #selector(quickPause), keyEquivalent: "").target = self
        }
        if running {
            menu.addItem(withTitle: Constants.Copy.orbActionExitSession, action: #selector(quickExit), keyEquivalent: "").target = self
        }
        menu.addItem(withTitle: Constants.Copy.orbActionSettings, action: #selector(quickSettings), keyEquivalent: "").target = self
        NSMenu.popUpContextMenu(menu, with: event, for: orb.contentViewForMenu ?? NSView())
    }

    @objc private func quickPause() { appState?.send(.userPaused) }
    @objc private func quickExit() { appState?.send(.userExited) }
    @objc private func quickSettings() { showSettings() }

    // MARK: Window helpers

    private func makeCardPanel(_ view: some View, app: AppState, level: NSWindow.Level) -> KeyablePanel {
        let host = NSHostingView(rootView: AnyView(view.environmentObject(app)))
        host.layoutSubtreeIfNeeded()
        let size = host.fittingSize
        let panel = KeyablePanel(contentRect: CGRect(origin: .zero, size: size),
                                 styleMask: [.borderless, .nonactivatingPanel], backing: .buffered, defer: false)
        panel.isOpaque = false
        panel.backgroundColor = .clear
        panel.hasShadow = true
        panel.level = level
        panel.collectionBehavior = [.canJoinAllSpaces, .fullScreenAuxiliary]
        panel.isReleasedWhenClosed = false
        panel.contentView = host
        panel.setContentSize(size)
        return panel
    }

    private func makeStandardWindow(title: String, view: some View) -> NSWindow {
        let window = NSWindow(contentRect: CGRect(x: 0, y: 0, width: 480, height: 440),
                              styleMask: [.titled, .closable, .miniaturizable], backing: .buffered, defer: false)
        window.title = title
        window.contentView = NSHostingView(rootView: view)
        window.isReleasedWhenClosed = false
        window.center()
        return window
    }

    private func present(_ window: NSWindow) {
        NSApp.activate(ignoringOtherApps: true)
        window.makeKeyAndOrderFront(nil)
    }

    private func placeNearOrb(_ panel: NSPanel) {
        let vb = screen.visibleBounds()
        let orbFrame = orb.currentFrame
        let size = panel.frame.size
        var x = orbFrame.minX - size.width - 12
        if x < vb.minX + 8 { x = orbFrame.maxX + 12 }
        x = min(max(x, vb.minX + 8), vb.maxX - size.width - 8)
        var y = orbFrame.maxY - size.height
        y = min(max(y, vb.minY + 8), vb.maxY - size.height - 8)
        panel.setFrameOrigin(CGPoint(x: x, y: y))
    }

    private func center(_ panel: NSPanel) {
        let vb = screen.visibleBounds()
        let size = panel.frame.size
        panel.setFrameOrigin(CGPoint(x: vb.midX - size.width / 2, y: vb.midY - size.height / 2))
    }

    private func dismiss(_ panel: inout NSPanel?) { panel?.orderOut(nil); panel = nil }
    private func dismiss(_ window: inout NSWindow?) { window?.orderOut(nil); window = nil }

    static func openSystemCameraPrefs() {
        if let url = URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Camera") {
            NSWorkspace.shared.open(url)
        }
    }
}
