// SessionCoordinator.swift — applies SessionEffect side effects to services and window controllers (canon §2, §5).
//
// Thin glue: the reducer decides everything, the coordinator only executes ordered effects against
// the window controllers, timer, audio, and presence services. It calls back into AppState.send for
// events generated by those services (timer ticks, presence, countdown completion, UI button taps).

import AppKit
import SwiftUI

final class SessionCoordinator {
    weak var appState: AppState?

    private let settings: SettingsStore
    private let store: SessionStore
    private let screen = ScreenManager()

    // Services
    private let voice: VoicePrompting = VoicePromptService()
    private let alarm: AlarmPlaying = AlarmService()
    private let simulated = SimulatedPresenceService()
    private let permission = CameraPermissionService()
    private let screenPermission = ScreenAnalysisPermissionService()
    private let screenAnalysis = ScreenAnalysisService()
    private var presence: PresenceDetecting?
    private let timer = SessionTimer()

    // Window controllers
    private lazy var orb = FocusOrbWindowController(
        app: appState!, positionStore: OrbPositionStore(settings: settings), screen: screen)
    private let aura: AuraWindowController

    // Transient windows
    private var startPanel: NSPanel?
    private var countdownWindow: NSWindow?
    private var hudPanel: NSPanel?
    private var awayPanel: NSPanel?
    private var completionPanel: NSPanel?
    private var nudgePanel: NSPanel?
    private var settingsWindow: NSWindow?
    private var historyWindow: NSWindow?
    private var onboardingWindow: NSWindow?

    init(settings: SettingsStore, store: SessionStore) {
        self.settings = settings
        self.store = store
        self.aura = AuraWindowController(settings: settings, screen: screen)

        timer.onTick = { [weak self] delta in self?.appState?.send(.tick(deltaSeconds: delta)) }
        screen.onScreenParametersChanged = { [weak self] in
            self?.orb.clampIntoVisibleBounds()
            self?.aura.rebuildWindows()
        }
        screen.startObservingScreenChanges()
    }

    /// Called by AppState after it constructs the coordinator, once `appState` is available.
    /// Wires the orb here (not in init) because the lazy orb needs a non-nil `appState`.
    func attach(_ appState: AppState) {
        self.appState = appState
        orb.onClick = { [weak self] in self?.handleOrbClick() }
        orb.onHoverChanged = { [weak self] hovering in self?.appState?.orbHovered = hovering }
        orb.onLongPressBegan = { [weak self] in self?.beginQuickStart() ?? false }
        orb.onLongPressMoved = { [weak self] point in self?.quickStartMoved(point) }
        orb.onLongPressEnded = { [weak self] point in self?.finishQuickStart(point) }
        orb.onSecondaryClick = { [weak self] event in self?.showOrbQuickActions(event) }
    }

    /// Click toggle (canon §13 #25/#27): red sleep → green prepare. During a RUNNING session a
    /// click must never exit directly — it asks for confirmation (aura flashes red).
    private func handleOrbClick() {
        switch appState?.context.state {
        case .idle:      appState?.send(.orbClicked)
        case .preparing: appState?.send(.cancelPreparing)
        case .countdown: appState?.send(.userExited)      // T5 abort — cheap, nothing saved
        case .active, .warning, .manualPaused:
            requestExitConfirmation()
        case .away, .recovering, .completed, .exited, nil:
            break                                          // their own cards are already on screen
        }
    }

    // MARK: Exit confirmation (canon §13 #27)

    private var exitConfirmPanel: NSPanel?

    private func requestExitConfirmation() {
        guard let app = appState, app.context.state.isRunning, exitConfirmPanel == nil else { return }
        aura.setState(.red)   // everything turns red while the question is up
        let view = ExitConfirmView(
            onStay: { [weak self] in self?.dismissExitConfirm(restoreAura: true) },
            onExit: { [weak self] in
                self?.dismissExitConfirm(restoreAura: false)
                self?.appState?.send(.userExited)
            })
        let panel = makeCardPanel(view, app: app, level: .screenSaver)
        center(panel)
        exitConfirmPanel = panel
        NSApp.activate(ignoringOtherApps: true)
        panel.makeKeyAndOrderFront(nil)
    }

    private func dismissExitConfirm(restoreAura: Bool) {
        exitConfirmPanel?.orderOut(nil)
        exitConfirmPanel = nil
        if restoreAura, let state = appState?.context.state {
            aura.setState(Self.auraState(for: state))
        }
    }

    private static func auraState(for state: SessionState) -> AuraState {
        switch state {
        case .active: return .green
        case .warning: return .yellow
        case .away, .recovering: return .red
        case .manualPaused: return .dimmed
        default: return .hidden
        }
    }

    // MARK: Orb + menu-driven windows

    func showOrb() { orb.show() }

    func showSettings() {
        guard let app = appState else { return }
        if let w = settingsWindow { present(w); return }
        let view = SettingsView(
            onClearData: { [weak self] in try? self?.store.clear() },
            onResetOrb: { [weak self] in self?.orb.resetToDefault() },
            onOpenSystemCamera: { Self.openSystemCameraPrefs() }
        ).environmentObject(app)
        let w = makeStandardWindow(title: "Hyperfocus Settings", view: view)
        settingsWindow = w
        present(w)
    }

    func showHistory() {
        historyWindow?.orderOut(nil)
        let view = HistoryView(sessions: store.all())
        let w = makeStandardWindow(title: "Session History", view: view)
        historyWindow = w
        present(w)
    }

    /// Launch-time reminder when camera permission is still missing after onboarding (canon #27):
    /// the product's core feature needs it, so ask up front — never right before a session.
    private var permissionNudgeWindow: NSWindow?

    func showPermissionNudgeIfNeeded() {
        guard settings.onboardingCompleted, settings.useCameraForPresence,
              !permission.isAuthorized, permissionNudgeWindow == nil else { return }
        let close: () -> Void = { [weak self] in
            self?.permissionNudgeWindow?.orderOut(nil)
            self?.permissionNudgeWindow = nil
        }
        let view = PermissionNudgeView(
            canPrompt: permission.canPrompt,
            onEnable: { [weak self] in self?.permission.requestAccess { _ in close() } },
            onOpenSettings: { Self.openSystemCameraPrefs(); close() },
            onLater: close)
        let w = makeStandardWindow(title: "Hyperfocus needs your camera", view: view,
                                   size: CGSize(width: 430, height: 280))
        permissionNudgeWindow = w
        present(w)
    }

    func showOnboarding() {
        let closeOnboarding: () -> Void = { [weak self] in
            self?.settings.onboardingCompleted = true
            self?.onboardingWindow?.orderOut(nil)
            self?.onboardingWindow = nil
        }
        let view = OnboardingView(
            requestCamera: { [weak self] done in self?.permission.requestAccess(completion: done) },
            requestScreen: { [weak self] done in self?.screenPermission.requestAccess(completion: done) },
            onStartFirstSession: { [weak self] mission, minutes in
                closeOnboarding()
                // Activation moment: the user leaves onboarding inside a running session.
                self?.appState?.quickStart(minutes: minutes, mission: mission)
            },
            onFinish: closeOnboarding)
        let w = makeStandardWindow(title: "Welcome to Hyperfocus", view: view,
                                   size: CGSize(width: 480, height: 500))
        onboardingWindow = w
        present(w)
    }

    // MARK: Effect execution

    func perform(_ effects: [SessionEffect]) {
        for effect in effects { apply(effect) }
    }

    private func apply(_ effect: SessionEffect) {
        switch effect {
        case .showStartCard:            showStartCard()
        case .hideStartCard:            dismiss(&startPanel)
        case .showCountdown:            showCountdown()
        case .dismissCountdown:         dismiss(&countdownWindow)
        case .setAura(let state):       aura.setState(state)
        case .startTimer:               appState?.markTimerStarted(); timer.start(); showHUD(); startScreenAnalysis()
        case .pauseTimer, .resumeTimer: break   // SessionTimer is a continuous heartbeat; the reducer accounts per state
        case .stopTimer:                appState?.markSessionEnded(); timer.stop(); dismiss(&hudPanel); screenAnalysis.stop(); dismiss(&nudgePanel); dismissExitConfirm(restoreAura: false)
        case .startCameraWarmup:        startPresence(warmup: true)
        case .startPresenceDetection:   startPresence(warmup: false)
        case .stopCamera:               presence?.stop(); presence = nil
        case .startAlarm:               if settings.alarmEnabled { alarm.start(volume: alarmVolume()) }
        case .stopAlarm:                alarm.stop()
        case .playVoice(let line):      if settings.voicePromptsEnabled { voice.speak(line, persona: settings.voicePersona) }
        case .showAwayCard:             dismissExitConfirm(restoreAura: false); showAwayCard()
        case .hideAwayCard:             dismiss(&awayPanel)
        case .showRecoveryCountdown, .hideRecoveryCountdown: break   // AwayModeView reacts to state == .recovering
        case .showCompletion:           showCompletion()
        case .hideCompletion:           dismiss(&completionPanel)
        case .saveSession(let status):  appState?.persist(status)
        case .orbFlash:                 break   // FocusOrbView reacts to the state change to .idle
        }
    }

    // MARK: Presence

    private func startPresence(warmup: Bool) {
        let usingSimulated = appState?.useSimulatedCamera ?? false
        if presence == nil {
            let service: PresenceDetecting = usingSimulated ? simulated : CameraPresenceService()
            service.onEvent = { [weak self] event in
                switch event {
                case .facePresent:          self?.appState?.send(.facePresenceChanged(true))
                case .faceMissing:          self?.appState?.send(.facePresenceChanged(false))
                case .cameraState(let s):   self?.appState?.send(.cameraStateChanged(s))
                }
            }
            presence = service
        }
        // NEVER prompt for permission at session start (canon §13 #27) — permission is collected in
        // onboarding or by the launch nudge. If unauthorized here, the service emits .notAuthorized
        // and the reducer degrades to no-camera semantics silently.
        beginPresence(warmup: warmup)
    }

    private func beginPresence(warmup: Bool) {
        if warmup { presence?.startWarmup() } else { presence?.startDetection() }
    }

    // MARK: Quick start (long-press radial, canon §13 #25)

    private var quickStartChips: [(panel: NSPanel, minutes: Int)] = []
    private let quickStartModel = QuickStartModel()

    /// Long-press began: fade in the 3 most recent durations around the orb (left/right/below by
    /// preference, falling back to free slots when the orb is snapped to an edge or corner).
    /// Returns whether quick-start was actually shown.
    @discardableResult
    private func beginQuickStart() -> Bool {
        guard let app = appState, app.context.state == .idle, quickStartChips.isEmpty else { return false }
        let durations = app.recentDurationsMinutes()
        let orbFrame = orb.currentFrame
        let vb = orb.currentVisibleBounds          // the orb's own screen, not the key window's
        var occupied: [CGRect] = []

        for (index, minutes) in durations.enumerated() {
            let panel = makeCardPanel(
                QuickStartChipView(minutes: minutes, index: index, model: quickStartModel),
                app: app, level: .statusBar)
            let origin = chipOrigin(index: index, size: panel.frame.size,
                                    orbFrame: orbFrame, vb: vb, occupied: occupied)
            panel.setFrameOrigin(origin)
            panel.orderFrontRegardless()
            occupied.append(CGRect(origin: origin, size: panel.frame.size))
            quickStartChips.append((panel, minutes))
        }
        return true
    }

    /// First candidate slot that fits inside the visible bounds without covering the orb or another
    /// chip; falls back to a clamped preferred slot (worst case: orb wedged into a tiny screen).
    private func chipOrigin(index: Int, size: CGSize, orbFrame: CGRect, vb: CGRect,
                            occupied: [CGRect]) -> CGPoint {
        let gap: CGFloat = 10
        let left   = CGPoint(x: orbFrame.minX - size.width - gap, y: orbFrame.midY - size.height / 2)
        let right  = CGPoint(x: orbFrame.maxX + gap, y: orbFrame.midY - size.height / 2)
        let below  = CGPoint(x: orbFrame.midX - size.width / 2, y: orbFrame.minY - size.height - gap)
        let below2 = CGPoint(x: below.x, y: below.y - size.height - 6)
        let above  = CGPoint(x: orbFrame.midX - size.width / 2, y: orbFrame.maxY + gap)

        let preferred: [CGPoint]
        switch index {
        case 0:  preferred = [left, below, below2, above, right]
        case 1:  preferred = [right, below, below2, above, left]
        default: preferred = [below, below2, above, left, right]
        }
        for candidate in preferred {
            let rect = CGRect(origin: candidate, size: size)
            if vb.insetBy(dx: 4, dy: 4).contains(rect)
                && !rect.intersects(orbFrame.insetBy(dx: -4, dy: -4))
                && !occupied.contains(where: { $0.insetBy(dx: -4, dy: -4).intersects(rect) }) {
                return candidate
            }
        }
        var fallback = preferred[0]
        fallback.x = min(max(fallback.x, vb.minX + 4), vb.maxX - size.width - 4)
        fallback.y = min(max(fallback.y, vb.minY + 4), vb.maxY - size.height - 4)
        return fallback
    }

    /// Drag while holding: highlight the chip under the pointer (hover doesn't fire during a drag).
    private func quickStartMoved(_ screenPoint: NSPoint) {
        guard !quickStartChips.isEmpty else { return }
        quickStartModel.highlighted = quickStartChips.firstIndex { $0.panel.frame.contains(screenPoint) }
    }

    /// Release: start immediately if the pointer is over a chip; otherwise just dismiss.
    private func finishQuickStart(_ screenPoint: NSPoint) {
        let hit = quickStartChips.first { $0.panel.frame.contains(screenPoint) }
        for chip in quickStartChips { chip.panel.orderOut(nil) }
        quickStartChips.removeAll()
        quickStartModel.highlighted = nil
        if let hit { appState?.quickStart(minutes: hit.minutes) }
    }

    // MARK: Screen analysis (local distraction detection)

    private func startScreenAnalysis() {
        guard settings.useScreenAnalysis else { return }
        screenAnalysis.onDistraction = { [weak self] _ in self?.showNudge() }
        screenAnalysis.start()   // no-op unless Screen Recording is authorized
    }

    private func showNudge() {
        guard let app = appState, nudgePanel == nil else { return }
        let mission = app.context.config?.mission ?? "your task"
        let panel = makeCardPanel(NudgeView(mission: mission), app: app, level: .floating)
        placeNearOrb(panel)
        nudgePanel = panel
        panel.orderFrontRegardless()
        DispatchQueue.main.asyncAfter(deadline: .now() + 6) { [weak self] in
            self?.nudgePanel?.orderOut(nil)
            self?.nudgePanel = nil
        }
    }

    private func alarmVolume() -> Float {
        let base = Float(settings.soundVolume)
        let mult = Float(Constants.IntensityTuning.alarmVolumeMultiplier(
            for: appState?.context.config?.intensity ?? .cinematic))
        return min(1, base * mult)
    }

    // MARK: Cards

    private func showStartCard() {
        guard startPanel == nil, let app = appState else { return }
        let view = StartSessionView(
            onStart: { [weak self] config in self?.appState?.send(.enterHyperfocus(config)) },
            onCancel: { [weak self] in self?.appState?.send(.cancelPreparing) }
        )
        let panel = makeCardPanel(view, app: app, level: .statusBar)
        placeNearOrb(panel)
        startPanel = panel
        NSApp.activate(ignoringOtherApps: true)
        panel.makeKeyAndOrderFront(nil)
    }

    private func showCountdown() {
        guard countdownWindow == nil, let app = appState else { return }
        let frame = screen.mainScreenFrame()
        let view = CountdownOverlayView(
            onFinished: { [weak self] in self?.appState?.send(.countdownCompleted) },
            onAbort: { [weak self] in self?.appState?.send(.userExited) }
        ).environmentObject(app)

        let window = KeyablePanel(contentRect: frame, styleMask: [.borderless, .nonactivatingPanel],
                                  backing: .buffered, defer: false)
        window.isOpaque = false
        window.backgroundColor = .clear
        window.hasShadow = false
        window.level = .screenSaver
        window.collectionBehavior = [.canJoinAllSpaces, .fullScreenAuxiliary]
        window.isReleasedWhenClosed = false
        let host = NSHostingView(rootView: view)
        host.frame = CGRect(origin: .zero, size: frame.size)
        host.autoresizingMask = [.width, .height]
        window.contentView = host
        window.setFrame(frame, display: true)
        countdownWindow = window
        NSApp.activate(ignoringOtherApps: true)
        window.makeKeyAndOrderFront(nil)      // key so Esc (onExitCommand) aborts
    }

    private func showHUD() {
        guard hudPanel == nil, let app = appState else { return }
        let view = ActiveHUDView(onExit: { [weak self] in self?.requestExitConfirmation() })
        let panel = makeCardPanel(view, app: app, level: .statusBar)
        placeNearOrb(panel)
        hudPanel = panel
        panel.orderFrontRegardless()
    }

    private func showAwayCard() {
        guard awayPanel == nil, let app = appState else { return }
        let view = AwayModeView(
            onReturn: { [weak self] in self?.appState?.send(.facePresenceChanged(true)) },
            onExit: { [weak self] in self?.appState?.send(.userExited) }
        )
        let panel = makeCardPanel(view, app: app, level: .screenSaver)
        center(panel)
        awayPanel = panel
        NSApp.activate(ignoringOtherApps: true)
        panel.orderFrontRegardless()
    }

    private func showCompletion() {
        guard completionPanel == nil, let app = appState else { return }
        let view = CompletionView(onResult: { [weak self] status, next in
            self?.appState?.send(.resultSaved(status, nextAction: next))
        })
        let panel = makeCardPanel(view, app: app, level: .floating)
        center(panel)
        completionPanel = panel
        NSApp.activate(ignoringOtherApps: true)
        panel.makeKeyAndOrderFront(nil)
    }

    private func showOrbQuickActions(_ event: NSEvent) {
        let menu = NSMenu()
        let running = appState?.context.state.isRunning ?? false
        if appState?.context.state == .active {
            menu.addItem(withTitle: Constants.Copy.orbActionPause, action: #selector(quickPause), keyEquivalent: "").target = self
        }
        if running {
            menu.addItem(withTitle: Constants.Copy.orbActionExitSession, action: #selector(quickExit), keyEquivalent: "").target = self
        }
        menu.addItem(withTitle: Constants.Copy.orbActionSettings, action: #selector(quickSettings), keyEquivalent: "").target = self
        NSMenu.popUpContextMenu(menu, with: event, for: orb.contentViewForMenu ?? NSView())
    }

    @objc private func quickPause() { appState?.send(.userPaused) }
    @objc private func quickExit() { appState?.send(.userExited) }
    @objc private func quickSettings() { showSettings() }

    // MARK: Window helpers

    private func makeCardPanel(_ view: some View, app: AppState, level: NSWindow.Level) -> KeyablePanel {
        let host = NSHostingView(rootView: AnyView(view.environmentObject(app)))
        host.layoutSubtreeIfNeeded()
        let size = host.fittingSize
        let panel = KeyablePanel(contentRect: CGRect(origin: .zero, size: size),
                                 styleMask: [.borderless, .nonactivatingPanel], backing: .buffered, defer: false)
        panel.isOpaque = false
        panel.backgroundColor = .clear
        // No system window shadow: it draws a rectangular shadow/hairline box around the
        // transparent window edges ("странная обводка"); cards carry their own SwiftUI shadows.
        panel.hasShadow = false
        panel.level = level
        panel.collectionBehavior = [.canJoinAllSpaces, .fullScreenAuxiliary]
        panel.isReleasedWhenClosed = false
        panel.contentView = host
        panel.setContentSize(size)
        return panel
    }

    private func makeStandardWindow(title: String, view: some View,
                                    size: CGSize = CGSize(width: 480, height: 440)) -> NSWindow {
        let window = NSWindow(contentRect: CGRect(origin: .zero, size: size),
                              styleMask: [.titled, .closable, .miniaturizable], backing: .buffered, defer: false)
        window.title = title
        window.contentView = NSHostingView(rootView: view)
        window.isReleasedWhenClosed = false
        window.center()
        return window
    }

    private func present(_ window: NSWindow) {
        NSApp.activate(ignoringOtherApps: true)
        window.makeKeyAndOrderFront(nil)
    }

    private func placeNearOrb(_ panel: NSPanel) {
        let vb = orb.currentVisibleBounds
        let orbFrame = orb.currentFrame
        let size = panel.frame.size
        var x = orbFrame.minX - size.width - 12
        if x < vb.minX + 8 { x = orbFrame.maxX + 12 }
        x = min(max(x, vb.minX + 8), vb.maxX - size.width - 8)
        var y = orbFrame.maxY - size.height
        y = min(max(y, vb.minY + 8), vb.maxY - size.height - 8)
        panel.setFrameOrigin(CGPoint(x: x, y: y))
    }

    private func center(_ panel: NSPanel) {
        let vb = screen.visibleBounds()
        let size = panel.frame.size
        panel.setFrameOrigin(CGPoint(x: vb.midX - size.width / 2, y: vb.midY - size.height / 2))
    }

    private func dismiss(_ panel: inout NSPanel?) { panel?.orderOut(nil); panel = nil }
    private func dismiss(_ window: inout NSWindow?) { window?.orderOut(nil); window = nil }

    static func openSystemCameraPrefs() {
        if let url = URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Camera") {
            NSWorkspace.shared.open(url)
        }
    }

    #if DEBUG
    /// Input self-test: asks the WINDOW SERVER which window would receive a click at points across
    /// the orb (NSWindow.windowNumber(at:) honors per-pixel transparency). MISS = click-through bug.
    func runOrbHitSelfTest() {
        guard let orbNumber = orb.windowNumber, orb.isVisible else {
            NSLog("HFTEST no orb panel visible"); return
        }
        let f = orb.currentFrame
        let probes: [(String, CGPoint)] = [
            ("center",       CGPoint(x: f.midX, y: f.midY)),
            ("hollow+4",     CGPoint(x: f.midX + 4, y: f.midY)),
            ("ring-right",   CGPoint(x: f.midX + 14, y: f.midY)),
            ("glow-24",      CGPoint(x: f.midX + 24, y: f.midY)),
            ("corner+6",     CGPoint(x: f.minX + 6, y: f.minY + 6)),
        ]
        var interceptors = Set<Int>()
        for (name, p) in probes {
            let hit = NSWindow.windowNumber(at: p, belowWindowWithWindowNumber: 0)
            if hit != orbNumber { interceptors.insert(hit) }
            NSLog("HFTEST probe=%@ hit=%d orb=%d %@", name, hit, orbNumber,
                  hit == orbNumber ? "OK" : "MISS")
        }
        // Identify every on-screen window that intersects the orb frame: owner, layer, alpha, bounds.
        let info = CGWindowListCopyWindowInfo([.optionOnScreenOnly], kCGNullWindowID) as? [[String: Any]] ?? []
        for w in info {
            guard let num = w[kCGWindowNumber as String] as? Int,
                  let b = w[kCGWindowBounds as String] as? [String: CGFloat] else { continue }
            let isInterceptor = interceptors.contains(num)
            let owner = w[kCGWindowOwnerName as String] as? String ?? "?"
            let layer = w[kCGWindowLayer as String] as? Int ?? -1
            let alpha = w[kCGWindowAlpha as String] as? Double ?? -1
            // CGWindow bounds are top-left-origin; just log raw and match by number/orb proximity.
            if isInterceptor || num == orbNumber {
                NSLog("HFTEST window num=%d owner=%@ layer=%d alpha=%.3f bounds={%.0f,%.0f %.0fx%.0f}%@",
                      num, owner, layer, alpha, b["X"] ?? -1, b["Y"] ?? -1,
                      b["Width"] ?? -1, b["Height"] ?? -1, isInterceptor ? " <-- INTERCEPTOR" : " (orb)")
            }
        }

        // Panel flags — the window-server treats the whole panel as click-through; find out why.
        if let panel = orb.debugPanel {
            NSLog("HFTEST flags ignoresMouse=%d styleMask=%lu level=%ld visible=%d alpha=%.2f opaque=%d hidesOnDeactivate=%d becomesKeyOnlyIfNeeded=%d canBecomeKey=%d",
                  panel.ignoresMouseEvents ? 1 : 0, panel.styleMask.rawValue, panel.level.rawValue,
                  panel.isVisible ? 1 : 0, panel.alphaValue, panel.isOpaque ? 1 : 0,
                  panel.hidesOnDeactivate ? 1 : 0, panel.becomesKeyOnlyIfNeeded ? 1 : 0,
                  panel.canBecomeKey ? 1 : 0)
        }

        // CONTROL: a plain opaque borderless window at screen center — does windowNumber(at:) see
        // our own app's windows at all? Validates the probe API itself.
        let vb = screen.visibleBounds()
        let ctrlFrame = CGRect(x: vb.midX - 50, y: vb.midY - 50, width: 100, height: 100)
        let ctrl = NSWindow(contentRect: ctrlFrame, styleMask: [.borderless], backing: .buffered, defer: false)
        ctrl.backgroundColor = .red
        ctrl.level = .statusBar
        ctrl.orderFrontRegardless()
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) { [weak self] in
            let hit = NSWindow.windowNumber(at: CGPoint(x: ctrlFrame.midX, y: ctrlFrame.midY),
                                            belowWindowWithWindowNumber: 0)
            NSLog("HFTEST control-window hit=%d ctrl=%d %@", hit, ctrl.windowNumber,
                  hit == ctrl.windowNumber ? "API-OK" : "API-MISS")
            ctrl.orderOut(nil)

            // PIPELINE: synthetic mouseDown+Up sent directly to the panel — verifies container →
            // coordinator → reducer wiring independent of window-server routing.
            self?.runSyntheticClick()
        }
    }

    private func runSyntheticClick() {
        guard let panel = orb.debugPanel, let app = appState else { return }
        let pt = NSPoint(x: panel.frame.width / 2, y: panel.frame.height / 2)
        func ev(_ type: NSEvent.EventType) -> NSEvent? {
            NSEvent.mouseEvent(with: type, location: pt, modifierFlags: [],
                               timestamp: ProcessInfo.processInfo.systemUptime,
                               windowNumber: panel.windowNumber, context: nil,
                               eventNumber: 0, clickCount: 1, pressure: 1)
        }
        let before = app.context.state
        if let down = ev(.leftMouseDown), let up = ev(.leftMouseUp) {
            panel.sendEvent(down)
            panel.sendEvent(up)
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
            NSLog("HFTEST synthetic-click stateBefore=%@ stateAfter=%@ %@",
                  before.rawValue, app.context.state.rawValue,
                  app.context.state == .preparing ? "PIPELINE-OK" : "PIPELINE-MISS")
        }
    }
    #endif
}
