// UpdaterService.swift — Sparkle auto-update (canon #42): the app keeps itself current.
// Feed: https://hyperfocus.monster/appcast.xml (docs/appcast.xml, regenerated by release.sh).
// Checks run automatically (SUEnableAutomaticChecks); the menu row triggers a manual check.
// EdDSA-signed updates; the private key lives in the developer keychain, never in the repo.

import AppKit
import Sparkle

final class UpdaterService {
    static let shared = UpdaterService()

    private let controller: SPUStandardUpdaterController

    private init() {
        // starting the updater immediately schedules the background daily check
        controller = SPUStandardUpdaterController(startingUpdater: true,
                                                  updaterDelegate: nil,
                                                  userDriverDelegate: nil)
    }

    /// Menu action: bring the (LSUIElement) app forward so Sparkle's window is visible, then check.
    func checkForUpdates() {
        NSApp.activate(ignoringOtherApps: true)
        controller.checkForUpdates(nil)
    }
}
